export const healthyEatingTips = [
  "Eat a variety of colorful vegetables every day.",
  "Drink at least 8 glasses of water daily.",
  "Choose whole grains over refined grains.",
  "Include lean protein in every meal.",
  "Limit added sugars in your diet.",
  "Snack on nuts and seeds for healthy fats.",
  "Eat fruit instead of drinking fruit juice.",
  "Prepare meals at home to control ingredients.",
  "Read food labels to understand what you're eating.",
  "Practice mindful eating by slowing down.",
  "Don't skip breakfast; it kickstarts your metabolism.",
  "Incorporate legumes like lentils and beans.",
  "Choose healthy cooking methods like steaming or grilling.",
  "Keep healthy snacks readily available.",
  "Eat smaller, more frequent meals if it helps.",
  "Avoid processed foods as much as possible.",
  "Include fermented foods for gut health.",
  "Eat fatty fish rich in omega-3s twice a week.",
  "Use herbs and spices instead of salt for flavor.",
  "Listen to your body's hunger and fullness cues.",
  "Plan your meals for the week ahead.",
  "Eat a balanced diet with protein, carbs, and fats.",
  "Choose low-fat dairy or dairy alternatives.",
  "Limit caffeine intake, especially in the afternoon.",
  "Avoid eating late at night.",
  "Try meatless Mondays.",
  "Eat seasonal produce for better nutrition.",
  "Keep a food diary to track your habits.",
  "Don't drink your calories; choose water or tea.",
  "Eat slowly to give your brain time to register fullness.",
  "Choose healthy fats like avocado and olive oil.",
  "Eat plenty of fiber for digestion.",
  "Avoid emotional eating; find other coping mechanisms.",
  "Cook in batches to save time and ensure healthy meals.",
  "Try new recipes to keep eating interesting.",
  "Eat breakfast like a king, lunch like a prince, dinner like a pauper.",
  "Choose baked or air-fried instead of deep-fried.",
  "Limit alcohol consumption.",
  "Eat a handful of berries for antioxidants.",
  "Include dark leafy greens in your salads.",
  "Don't shop for groceries when you're hungry.",
  "Choose unsweetened beverages.",
  "Eat slowly and chew your food thoroughly.",
  "Include probiotics in your diet.",
  "Eat a variety of protein sources.",
  "Limit intake of refined carbohydrates.",
  "Choose natural sweeteners like honey in moderation.",
  "Eat mindfully without distractions like TV.",
  "Keep your portion sizes in check.",
  "Eat a balanced diet to maintain energy levels.",
  "Try to eat at the same time every day.",
  "Choose whole fruits over dried fruits.",
  "Include cruciferous vegetables like broccoli.",
  "Limit intake of saturated fats.",
  "Avoid sugary snacks.",
  "Eat a variety of nuts.",
  "Choose lean cuts of meat.",
  "Drink water before meals.",
  "Eat fiber-rich foods to stay full longer.",
  "Limit intake of sodium.",
  "Eat a variety of seeds.",
  "Choose whole-grain bread.",
  "Eat plenty of vegetables.",
  "Limit intake of red meat.",
  "Choose healthy snacks like yogurt.",
  "Eat slowly to enjoy your food.",
  "Include healthy fats in your diet.",
  "Eat a variety of fruits.",
  "Limit intake of processed meats.",
  "Choose whole-grain pasta.",
  "Eat plenty of protein.",
  "Limit intake of sugary drinks.",
  "Choose healthy fats like nuts.",
  "Eat a variety of legumes.",
  "Limit intake of fried foods.",
  "Choose whole-grain cereals.",
  "Eat plenty of fiber.",
  "Limit intake of fast food.",
  "Choose healthy snacks like fruit.",
  "Eat a variety of vegetables.",
  "Limit intake of sweets.",
  "Choose whole-grain rice.",
  "Eat plenty of vitamins.",
  "Limit intake of high-calorie foods.",
  "Choose healthy fats like seeds.",
  "Eat a variety of grains.",
  "Limit intake of artificial ingredients.",
  "Choose whole-grain snacks.",
  "Eat plenty of minerals.",
  "Limit intake of unhealthy fats.",
  "Choose healthy snacks like vegetables.",
  "Eat a variety of proteins.",
  "Limit intake of refined sugars.",
  "Choose whole-grain crackers.",
  "Eat plenty of antioxidants.",
  "Limit intake of processed snacks.",
  "Choose healthy fats like avocado.",
  "Eat a variety of foods.",
  "Limit intake of unhealthy snacks.",
  "Enjoy your food!"
];
